plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/bluer/Documents/trae_projects/岭南所官网/sites/A-campus"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]